// Edit this file to update projects.
const projects = [
  {
    id: 1,
    name: 'Firee — Decentralized Marketplace',
    desc: 'End-to-end design and development of a decentralized marketplace. Dark, minimalist UI built with Next.js 14 and Tailwind CSS.',
    tags: ['Next.js', 'Tailwind CSS', 'Web3'],
    featured: true,
    accent: true,
    href: 'https://mp-firee.vercel.app/',
    liveUrl: 'https://mp-firee.vercel.app/',
    bgText: '01',
    bgTextColor: 'rgba(130,80,255,0.15)',
  },
  {
    id: 2,
    name: 'Lumina — AI Teaching Platform',
    desc: 'AI-powered teaching and learning platform. Personalized lesson generation, progress tracking, and an adaptive curriculum engine — built fullstack with Next.js and an AI agent backend.',
    tags: ['Next.js', 'AI', 'Fullstack'],
    featured: false,
    accent: false,
    comingSoon: true,
    bgText: 'LUMINA',
    bgTextColor: 'rgba(200,240,74,0.12)',
  },
  {
    id: 3,
    name: 'Amana Protocol — Decentralized Exchange',
    desc: 'A decentralized exchange interface with clean UI, featuring token swaps, liquidity pools, and on-chain trading built with Next.js and Tailwind CSS.',
    tags: ['Next.js', 'DEX', 'Web3'],
    featured: false,
    accent: false,
    href: 'https://amana-protocol.vercel.app/',
    liveUrl: 'https://amana-protocol.vercel.app/',
    bgText: '03',
    bgTextColor: 'rgba(200,240,74,0.15)',
  },
  {
    id: 4,
    name: 'RiskLens — Token Risk Scanner',
    desc: 'Automated token risk scanner for Solana & EVM chains. Turns raw on-chain signals into plain-language risk reports with score, warnings, and recommendations.',
    tags: ['Next.js', 'Web3', 'Security'],
    featured: false,
    accent: false,
    href: 'https://risklens-labs.vercel.app/',
    liveUrl: 'https://risklens-labs.vercel.app/',
    bgText: '04',
    bgTextColor: 'rgba(100,100,200,0.2)',
  },
]

export default projects
