// Edit this file to update projects.
const projects = [
  {
    id: 1,
    name: 'Firee — Decentralized Marketplace',
    desc: 'End-to-end design and development of a decentralized marketplace. Dark, minimalist UI built with Next.js 14 and Tailwind CSS.',
    tags: ['Next.js', 'Tailwind CSS', 'Web3'],
    featured: true,
    accent: true,
    href: 'https://mp-firee.vercel.app/',
    liveUrl: 'https://mp-firee.vercel.app/',
    bgText: '01',
    bgTextColor: 'rgba(130,80,255,0.15)',
  },
  {
    id: 2,
    name: 'Amana Protocol — Decentralized Exchange',
    desc: 'A decentralized exchange interface with clean UI, featuring token swaps, liquidity pools, and on-chain trading built with Next.js and Tailwind CSS.',
    tags: ['Next.js', 'DEX', 'Web3'],
    featured: false,
    accent: false,
    href: 'https://amana-protocol.vercel.app/',
    liveUrl: 'https://amana-protocol.vercel.app/',
    bgText: '02',
    bgTextColor: 'rgba(200,240,74,0.15)',
  },
  {
    id: 3,
    name: 'E-Commerce Mobile App',
    desc: 'A clean, conversion-focused mobile shopping experience redesigned from scratch using Figma and usability testing.',
    tags: ['UI/UX', 'Mobile'],
    featured: false,
    href: '#',
    comingSoon: true,
    bgColor: 'linear-gradient(135deg, #0d0d1f 0%, #131328 100%)',
    bgText: '03',
    bgTextColor: 'rgba(100,100,200,0.2)',
  },
  {
    id: 4,
    name: 'Agency Landing Page',
    desc: 'High-performance marketing site with scroll animations and micro-interactions, built for pixel-perfect precision.',
    tags: ['Frontend', 'HTML/CSS', 'JS'],
    featured: false,
    href: '#',
    comingSoon: true,
    bgColor: 'linear-gradient(135deg, #1a0d0d 0%, #2a1010 100%)',
    bgText: '04',
    bgTextColor: 'rgba(200,80,80,0.2)',
  },
]

export default projects
