// Edit this file to update your projects!
const projects = [
  {
    id: 1,
    name: 'Finance Dashboard App',
    desc: 'End-to-end design and development of a personal finance tracker. From user research and wireframes to a fully responsive React frontend.',
    tags: ['UI/UX', 'Figma', 'React'],
    featured: true,
    accent: true,
    href: '#',
    bgColor: 'linear-gradient(135deg, #1a1a1a 0%, #0d1f0d 100%)',
    bgText: '01',
    bgTextColor: 'rgba(200,240,74,0.15)',
  },
  {
    id: 2,
    name: 'E-Commerce Mobile App',
    desc: 'A clean, conversion-focused mobile shopping experience redesigned from scratch using Figma and usability testing.',
    tags: ['UI/UX', 'Mobile'],
    featured: false,
    href: '#',
    bgColor: 'linear-gradient(135deg, #0d0d1f 0%, #131328 100%)',
    bgText: '02',
    bgTextColor: 'rgba(100,100,200,0.2)',
  },
  {
    id: 3,
    name: 'Agency Landing Page',
    desc: 'High-performance marketing site with scroll animations and micro-interactions, built for pixel-perfect precision.',
    tags: ['Frontend', 'HTML/CSS', 'JS'],
    featured: false,
    href: '#',
    bgColor: 'linear-gradient(135deg, #1a0d0d 0%, #2a1010 100%)',
    bgText: '03',
    bgTextColor: 'rgba(200,80,80,0.2)',
  },
  {
    id: 4,
    name: 'SaaS Design System',
    desc: 'A scalable component library and design system built for a B2B SaaS product, covering 80+ components and tokens.',
    tags: ['Design System', 'Figma'],
    featured: false,
    href: '#',
    bgColor: 'linear-gradient(135deg, #0d1a14 0%, #0a160e 100%)',
    bgText: '04',
    bgTextColor: 'rgba(60,180,100,0.2)',
  },
]

export default projects
